/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as VendeurRouteImport } from './routes/vendeur'
import { Route as FicheIdRouteImport } from './routes/fiche.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPublicFedapayWebhookRouteImport } from './routes/api/public/fedapay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const VendeurRoute = VendeurRouteImport.update({
  id: '/vendeur',
  path: '/vendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const FicheIdRoute = FicheIdRouteImport.update({
  id: '/fiche/$id',
  path: '/fiche/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFedapayWebhookRoute = ApiPublicFedapayWebhookRouteImport.update({
  id: '/api/public/fedapay-webhook',
  path: '/api/public/fedapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/vendeur': typeof VendeurRoute
  '/fiche/$id': typeof FicheIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/fedapay-webhook': typeof ApiPublicFedapayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/vendeur': typeof VendeurRoute
  '/fiche/$id': typeof FicheIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/fedapay-webhook': typeof ApiPublicFedapayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/vendeur': typeof VendeurRoute
  '/fiche/$id': typeof FicheIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/fedapay-webhook': typeof ApiPublicFedapayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/carte'
    | '/vendeur'
    | '/fiche/$id'
    | '/api/auth/$'
    | '/api/public/fedapay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/carte'
    | '/vendeur'
    | '/fiche/$id'
    | '/api/auth/$'
    | '/api/public/fedapay-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/carte'
    | '/vendeur'
    | '/fiche/$id'
    | '/api/auth/$'
    | '/api/public/fedapay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CarteRoute: typeof CarteRoute
  VendeurRoute: typeof VendeurRoute
  FicheIdRoute: typeof FicheIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicFedapayWebhookRoute: typeof ApiPublicFedapayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendeur': {
      id: '/vendeur'
      path: '/vendeur'
      fullPath: '/vendeur'
      preLoaderRoute: typeof VendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiche/$id': {
      id: '/fiche/$id'
      path: '/fiche/$id'
      fullPath: '/fiche/$id'
      preLoaderRoute: typeof FicheIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fedapay-webhook': {
      id: '/api/public/fedapay-webhook'
      path: '/api/public/fedapay-webhook'
      fullPath: '/api/public/fedapay-webhook'
      preLoaderRoute: typeof ApiPublicFedapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CarteRoute: CarteRoute,
  VendeurRoute: VendeurRoute,
  FicheIdRoute: FicheIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicFedapayWebhookRoute: ApiPublicFedapayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
