import { useState } from "react";
import { ArrowLeft, ArrowRight, BadgeCheck, MapPin, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { MapCanvas } from "@/components/omni/MapCanvas";
import type { SellerOnboardingDraft } from "@/components/omni/vendor/SellerOnboardingFlow";

type Props = { center: { lat: number; lng: number }; saving: boolean; onSubmit: (draft: SellerOnboardingDraft) => Promise<void> };

export function CleanSellerOnboarding({ center, saving, onSubmit }: Props) {
  const [step, setStep] = useState(0);
  const [certificationReady, setCertificationReady] = useState(false);
  const [draft, setDraft] = useState<SellerOnboardingDraft>({ name: "", category: "", type: "fixe", phone: "", address: "", description: "", position: center });
  const patch = (next: Partial<SellerOnboardingDraft>) => setDraft((current) => ({ ...current, ...next }));

  function next() {
    if (step === 0 && draft.name.trim().length < 2) { toast.error("Indiquez le nom de votre facilité."); return; }
    if (step === 1 && !draft.category.trim()) { toast.error("Choisissez une catégorie."); return; }
    setStep((current) => Math.min(2, current + 1));
  }

  return (
    <main className="min-h-[100dvh] bg-[var(--omni-paper)] px-4 py-5 text-[var(--omni-ink)] sm:px-8 sm:py-8">
      <div className="mx-auto grid min-h-[calc(100dvh-2.5rem)] max-w-6xl items-center gap-5 lg:grid-cols-[.8fr_1.2fr]">
        <section className="rounded-[2rem] bg-[var(--omni-orange)] p-6 text-white shadow-[var(--omni-shadow-float)] sm:p-8"><p className="text-[10px] font-extrabold uppercase tracking-[0.17em] text-white/75">Créer une présence sur Omni</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-[-0.06em]">Votre facilité. Visible quand elle peut servir.</h1><p className="mt-4 text-sm leading-6 text-white/80">Après création ou claim, Omni demande une certification pour protéger les acheteurs et activer le listing.</p><div className="mt-7 space-y-3"><div className="rounded-2xl bg-white/12 p-4"><div className="flex items-center gap-2 font-extrabold"><BadgeCheck className="h-4 w-4" />Certification obligatoire</div><p className="mt-1 text-xs leading-5 text-white/75">Identité, compagnie, facilité et preuve du produit/service seront vérifiées par un admin.</p></div><div className="rounded-2xl bg-white/12 p-4"><div className="flex items-center gap-2 font-extrabold"><ShieldCheck className="h-4 w-4" />Bonus annoncé : 20 $</div><p className="mt-1 text-xs leading-5 text-white/75">Verrouillé jusqu’à vos trois premières ventes actives via Omni.</p></div></div></section>
        <section className="rounded-[2rem] border border-white/80 bg-white/78 p-4 shadow-[var(--omni-shadow-float)] backdrop-blur-xl sm:p-6"><div className="mb-6 flex items-center gap-2">{["Identité", "Position", "Certification"].map((label, index) => <div key={label} className="flex min-w-0 flex-1 items-center gap-2"><span className={index <= step ? "flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--omni-orange)] text-xs font-extrabold text-white" : "flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--omni-paper)] text-xs font-extrabold text-[var(--omni-ink-muted)]"}>{index + 1}</span><span className="truncate text-xs font-extrabold">{label}</span>{index < 2 ? <span className="h-px flex-1 bg-black/10" /> : null}</div>)}</div>
          {step === 0 ? <div className="space-y-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[var(--omni-orange-deep)]">Identité de la facilité</p><h2 className="mt-1 font-display text-2xl font-extrabold">Comment les acheteurs la trouveront ?</h2></div><label className="space-y-1.5"><span className="text-xs font-extrabold">Nom affiché</span><input className="omni-clean-field" value={draft.name} onChange={(event) => patch({ name: event.target.value })} placeholder="Ex. Atelier Kégué" autoFocus /></label><label className="space-y-1.5"><span className="text-xs font-extrabold">Catégorie</span><input className="omni-clean-field" value={draft.category} onChange={(event) => patch({ category: event.target.value })} placeholder="Ex. Maison, mode, matériaux" /></label><label className="space-y-1.5"><span className="text-xs font-extrabold">Type</span><select className="omni-clean-field" value={draft.type} onChange={(event) => patch({ type: event.target.value as SellerOnboardingDraft["type"] })}><option value="fixe">Facilité fixe</option><option value="mobile">Facilité mobile</option></select></label><label className="space-y-1.5 sm:col-span-2"><span className="text-xs font-extrabold">Contact vendeur</span><input className="omni-clean-field text-base" type="tel" value={draft.phone} onChange={(event) => patch({ phone: event.target.value })} placeholder="Téléphone de la facilité" autoComplete="tel" /></label></div> : null}
          {step === 1 ? <div className="space-y-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[var(--omni-orange-deep)]">Position</p><h2 className="mt-1 font-display text-2xl font-extrabold">Placez votre facilité sur la carte</h2></div><label className="space-y-1.5"><span className="text-xs font-extrabold">Adresse ou repère</span><input className="omni-clean-field" value={draft.address} onChange={(event) => patch({ address: event.target.value })} placeholder="Quartier, rue, repère" /></label><div className="relative h-64 overflow-hidden rounded-[1.5rem] border border-black/5"><MapCanvas facilities={[]} focus={draft.position} onMapClick={(coords) => patch({ position: coords })} className="h-full w-full" /><div className="pointer-events-none absolute bottom-3 left-3 rounded-full bg-white/85 px-3 py-2 text-xs font-extrabold shadow-sm"><MapPin className="mr-1 inline h-3.5 w-3.5 text-[var(--omni-orange)]" />Touchez pour corriger</div></div><button type="button" onClick={() => navigator.geolocation?.getCurrentPosition((position) => patch({ position: { lat: position.coords.latitude, lng: position.coords.longitude } }), () => toast.error("Position GPS indisponible."))} className="omni-clean-secondary-button min-h-11 w-full">Utiliser ma position</button></div> : null}
          {step === 2 ? <div className="space-y-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[var(--omni-orange-deep)]">Certification</p><h2 className="mt-1 font-display text-2xl font-extrabold">Préparez la preuve de confiance</h2><p className="mt-2 text-sm leading-6 text-[var(--omni-ink-muted)]">Votre facilité sera créée en attente de certification. Un admin vérifiera votre identité, votre compagnie, cette facilité et les produits/services que vous proposez.</p></div><div className="grid gap-2 sm:grid-cols-3"><div className="rounded-2xl bg-[var(--omni-paper)] p-3 text-xs font-bold">Identité vérifiée</div><div className="rounded-2xl bg-[var(--omni-paper)] p-3 text-xs font-bold">Facilité prouvée</div><div className="rounded-2xl bg-[var(--omni-paper)] p-3 text-xs font-bold">Offre réelle</div></div><label className="space-y-1.5"><span className="text-xs font-extrabold">Description (facultatif)</span><textarea className="omni-clean-field min-h-28" value={draft.description} onChange={(event) => patch({ description: event.target.value })} placeholder="Décrivez brièvement votre offre" maxLength={400} /></label><p className="rounded-2xl bg-[var(--omni-orange-wash)] p-4 text-sm font-bold text-[var(--omni-orange-deep)]">Après validation admin : statut Unconfirmed, jusqu’à 5 produits Free, puis Confirmed après 3 ventes Omni. Les 20 $ annoncés restent verrouillés jusqu’à ces 3 ventes et ne sont utilisables que sur Omni.</p><label className="flex items-start gap-3 rounded-2xl border border-black/5 bg-white/75 p-4 text-sm font-semibold"><input type="checkbox" checked={certificationReady} onChange={(event) => setCertificationReady(event.target.checked)} className="mt-1 h-5 w-5 shrink-0 accent-[var(--omni-orange)]" /><span>Je comprends que je dois fournir les preuves demandées et attendre la vérification admin avant de présenter cette facilité comme confirmée.</span></label></div> : null}
          <div className="mt-6 flex gap-2">{step > 0 ? <button type="button" onClick={() => setStep((current) => current - 1)} className="omni-clean-secondary-button min-h-12 flex-1"><ArrowLeft className="h-4 w-4" />Retour</button> : null}{step < 2 ? <button type="button" onClick={next} className="omni-clean-primary-button min-h-12 flex-1">Continuer<ArrowRight className="h-4 w-4" /></button> : <button type="button" onClick={() => certificationReady ? void onSubmit(draft) : toast.error("Confirmez la compréhension du parcours de certification.")} disabled={saving} className="omni-clean-primary-button min-h-12 flex-1">{saving ? "Création…" : "Créer et lancer la certification"}</button>}</div>
        </section>
      </div>
    </main>
  );
}
